# Generated by Django 4.0.4 on 2022-05-11 08:32

import apps.main_page.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='media/main_page_video_uploaded/%Y/%m/%d', validators=[apps.main_page.validators.validate_video_extension], verbose_name='Только ".MOV, .avi, .mp4, .webm, .mkv" форматы поддерживаются')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
